# network architecture
# encoder related
encoder: vgg_rnn
encoder_conf:
    rnn_type: lstm     # encoder architecture type
    bidirectional: True
    use_projection: True
    num_layers: 3
    hidden_size: 256
    output_size: 256

# decoder related
decoder: rnn
decoder_conf:
    num_layers: 2
    hidden_size: 256
    sampling_probability: 0
    att_conf:
        atype: location
        adim: 256
        aconv_chans: 10
        aconv_filts: 100

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.5

# minibatch related
batch_size: 15

# optimization related
optim: adadelta
max_epoch: 20
patience: 20

accum_grad: 2
